In [2]:
import torch
print(torch.__version__)

2.8.0


In [4]:
if torch.cuda.is_available():
    print("CUDA is available. You can use GPU acceleration.")
else:
    print("GPU is not available. Using CPU only")

GPU is not available. Using CPU only


# creating a Tensor

In [8]:
# using empty
a = torch.empty(2,3)
type(a)

torch.Tensor

In [9]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [10]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [12]:
# using rand
torch.rand(2,4)

tensor([[0.8559, 0.3666, 0.2492, 0.1448],
        [0.3520, 0.7972, 0.5228, 0.6389]])

In [17]:
torch.manual_seed(42)
torch.rand(2,4)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936]])

In [19]:
torch.manual_seed(100)
torch.rand(2,4)

tensor([[0.1117, 0.8158, 0.2626, 0.4839],
        [0.6765, 0.7539, 0.2627, 0.0428]])

In [23]:
# using tensor 
torch.tensor([[[1,2,3],[2,32,1]],[[1,2,3],[2,32,1]]])

tensor([[[ 1,  2,  3],
         [ 2, 32,  1]],

        [[ 1,  2,  3],
         [ 2, 32,  1]]])

In [32]:
# using arange
torch.arange(1,10,2)

# using linspace
torch.linspace(1,10,9) # linearly spaced tensor 

# using eye 
torch.eye(3) # identity matrix 3*3


tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

# Tensor shape

In [35]:
a = torch.tensor([[[1,2,3],[2,32,1]],[[1,2,3],[2,32,1]]])
a.shape

torch.Size([2, 2, 3])

In [36]:
torch.empty_like(a)

tensor([[[0, 0, 0],
         [0, 0, 0]],

        [[0, 0, 0],
         [0, 0, 0]]])

In [37]:
torch.ones_like(a)

tensor([[[1, 1, 1],
         [1, 1, 1]],

        [[1, 1, 1],
         [1, 1, 1]]])

In [38]:
torch.zeros_like(a)

tensor([[[0, 0, 0],
         [0, 0, 0]],

        [[0, 0, 0],
         [0, 0, 0]]])

# Tensor Datatypes

In [41]:
# find data types 
a.dtype

torch.int64

In [50]:
# assign dataa type

c = torch.tensor([1.0,2.0,3.0], dtype=torch.float32)
c

tensor([1., 2., 3.])

In [49]:
c.dtype

torch.float32

In [46]:
# assign dataa type

b = torch.tensor([1.0,2.0,3.0], dtype=torch.int16)
b.dtype

torch.int16

In [51]:
# U can even change the datatype of a variable 
c.to(torch.int16)

tensor([1, 2, 3], dtype=torch.int16)

In [53]:
torch.rand_like(a,dtype = torch.float32)

tensor([[[0.2080, 0.1180, 0.1217],
         [0.7356, 0.7118, 0.7876]],

        [[0.4183, 0.9014, 0.9969],
         [0.7565, 0.2239, 0.3023]]])

# Mathematical operations 

In [62]:
# 1. scalar operations 

x = torch.rand(2,2)
x

tensor([[0.4563, 0.3389],
        [0.6211, 0.5530]])

In [ ]:
# addition
x + 2
# substractions
x - 2
# multiplication
x*3
# integer division
(x*100) // 3


tensor([[15., 11.],
        [20., 18.]])

In [75]:
a = torch.rand(2,2)
b = torch.rand(2,2)

print(a)
print(b)

tensor([[0.6017, 0.4234],
        [0.5224, 0.4175]])
tensor([[0.0340, 0.9157],
        [0.3079, 0.6269]])


In [82]:
# element wise operartion
a + b
# substraction 
a - b
# multiplication 
a * b
# division 
a / b
# integer division
a // b
# power
a ** b
# mod
a % b

tensor([[0.0235, 0.4234],
        [0.2146, 0.4175]])

In [83]:
c = torch.tensor([1,-2,3,-4])

In [84]:
torch.abs(c)

tensor([1, 2, 3, 4])

In [85]:
# negative 
torch.neg(c)

tensor([-1,  2, -3,  4])

In [88]:
torch.round(torch.tensor([1.5,3.4,5.4]))

tensor([2., 3., 5.])

# Reduction operation 

In [100]:
e = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
e

tensor([[7., 9., 2.],
        [4., 6., 6.]])

In [101]:
# sum 
torch.sum(e)
torch.sum(e,dim=0) # column wise sum
torch.sum(e,dim=1) # row wise sum 


tensor([18., 16.])

In [103]:
# mean 
torch.mean(e)
torch.mean(e, dim=0)

tensor([5.5000, 7.5000, 4.0000])

In [104]:
torch.median(e)

tensor(6.)

In [108]:
torch.min(e)
torch.max(e)
torch.std(e)
torch.var(e)

tensor(5.8667)

In [ ]:
torch.argmax(e) # sabse bade element ka index

tensor(1)

In [110]:
torch.argmin(e) # sabse chhote element ka index

tensor(2)

# Matrix operations 

In [111]:
a = torch.randint(size=(2,3), low=0, high=10)
b = torch.randint(size=(3,2), low=0, high=10)

print(a)
print(b)

tensor([[8, 4, 9],
        [0, 7, 9]])
tensor([[2, 7],
        [0, 2],
        [4, 4]])


In [112]:
# matrix multiplication 
torch.matmul(a,b)

tensor([[ 52, 100],
        [ 36,  50]])

In [114]:
vec1 = torch.tensor([1,2])
vec2 = torch.tensor([3,4])

# dot product
torch.dot(vec1, vec2)

tensor(11)

In [ ]:
torch.transpose(a, 0, 1) # pehla kon and badme kon 0 and usk baad 1 

tensor([[8, 0],
        [4, 7],
        [9, 9]])

In [141]:
a = torch.tensor([[10,2,3],[4,43,6],[7,8,9]], dtype=torch.float32)
a

tensor([[10.,  2.,  3.],
        [ 4., 43.,  6.],
        [ 7.,  8.,  9.]])

In [142]:
torch.det(a)

tensor(2595.)

In [143]:
torch.inverse(a)

tensor([[ 0.1306,  0.0023, -0.0451],
        [ 0.0023,  0.0266, -0.0185],
        [-0.1037, -0.0254,  0.1626]])

In [144]:
# special functions
torch.log(a)

tensor([[2.3026, 0.6931, 1.0986],
        [1.3863, 3.7612, 1.7918],
        [1.9459, 2.0794, 2.1972]])

In [145]:
torch.exp(a)

tensor([[2.2026e+04, 7.3891e+00, 2.0086e+01],
        [5.4598e+01, 4.7278e+18, 4.0343e+02],
        [1.0966e+03, 2.9810e+03, 8.1031e+03]])

In [146]:
torch.sqrt(a)

tensor([[3.1623, 1.4142, 1.7321],
        [2.0000, 6.5574, 2.4495],
        [2.6458, 2.8284, 3.0000]])

In [147]:
torch.sigmoid(a)

tensor([[1.0000, 0.8808, 0.9526],
        [0.9820, 1.0000, 0.9975],
        [0.9991, 0.9997, 0.9999]])

In [149]:
torch.softmax(a, dim=1)

tensor([[9.9875e-01, 3.3504e-04, 9.1075e-04],
        [1.1548e-17, 1.0000e+00, 8.5330e-17],
        [9.0031e-02, 2.4473e-01, 6.6524e-01]])

# Inplace operations 

In [150]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)


tensor([[0.1879, 0.5534, 0.2682],
        [0.9556, 0.9761, 0.5934]])
tensor([[0.3124, 0.9431, 0.8519],
        [0.9815, 0.1132, 0.4783]])


In [151]:
m + n 

tensor([[0.5003, 1.4965, 1.1200],
        [1.9371, 1.0893, 1.0717]])

In [152]:
# I want to store the sum in the location of m only 
m.add_(n)

tensor([[0.5003, 1.4965, 1.1200],
        [1.9371, 1.0893, 1.0717]])

In [155]:
m

tensor([[0.5003, 1.4965, 1.1200],
        [1.9371, 1.0893, 1.0717]])

In [157]:
torch.sigmoid(m)

tensor([[0.6225, 0.8171, 0.7540],
        [0.8740, 0.7483, 0.7449]])

In [158]:
m.sigmoid_()

tensor([[0.6225, 0.8171, 0.7540],
        [0.8740, 0.7483, 0.7449]])

In [159]:
m 

tensor([[0.6225, 0.8171, 0.7540],
        [0.8740, 0.7483, 0.7449]])

# copying a tensor 

In [171]:
a = torch.rand(2,3)
a

tensor([[0.5662, 0.3503, 0.6555],
        [0.7667, 0.2269, 0.7555]])

In [172]:
b = a
b

tensor([[0.5662, 0.3503, 0.6555],
        [0.7667, 0.2269, 0.7555]])

In [173]:
a[0][0] = 22

In [174]:
a

tensor([[22.0000,  0.3503,  0.6555],
        [ 0.7667,  0.2269,  0.7555]])

In [175]:
b

tensor([[22.0000,  0.3503,  0.6555],
        [ 0.7667,  0.2269,  0.7555]])

In [178]:
b = a.clone()
b

tensor([[22.0000,  0.3503,  0.6555],
        [ 0.7667,  0.2269,  0.7555]])

In [179]:
a[0][0] = 10
a

tensor([[10.0000,  0.3503,  0.6555],
        [ 0.7667,  0.2269,  0.7555]])

In [180]:
b

tensor([[22.0000,  0.3503,  0.6555],
        [ 0.7667,  0.2269,  0.7555]])

# Reshaping tensors

In [182]:
a = torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [184]:
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [185]:
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [187]:
b = torch.rand(2,3,4)
b

tensor([[[0.0359, 0.3041, 0.9867, 0.1290],
         [0.6887, 0.1637, 0.0899, 0.3139],
         [0.1219, 0.3516, 0.2316, 0.2847]],

        [[0.3520, 0.2828, 0.2420, 0.4928],
         [0.5772, 0.3771, 0.2440, 0.8994],
         [0.1041, 0.9193, 0.6201, 0.3658]]])

In [193]:
# unsqueeze
c = torch.rand(226,226,3)
c.unsqueeze(1).shape

torch.Size([226, 1, 226, 3])